#!/usr/bin/env bash
# deps: dunst(dunstify), pamixer (PipeWire/PulseAudio)

step=10
case "$1" in
up)
  wpctl set-volume @DEFAULT_AUDIO_SINK@ "${step}%+"
  ;;
down)
  wpctl set-volume @DEFAULT_AUDIO_SINK@ "${step}%-"
  ;;
mute | toggle)
  wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
  ;;
esac

vol=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2*100)}')
muted=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED && echo true || echo false)

if [ "$muted" = "true" ]; then
  title="🔇 Muted"
  icon="audio-volume-muted"
else
  title="Volume"
  icon="audio-volume-medium"
fi

dunstify -a "volume" -i "$icon" -t 1200 \
  -h string:x-dunst-stack-tag:volume \
  -h int:value:"$vol" "$title" "$vol%"
